### ISSUE TITLE
Schedule in breaks/holidays

### ISSUE THREAD

**Issue by swillard13** [mburke13/scal#8]

**Comment by matthelb** [comment]
Unfortunately, parsing the HTML from [this](http://classes.usc.edu/term-20161/calendar/) may be the best/only way to accomplish this.

**Comment by matthelb** [comment]
Nevermind, doing it the stupid way. Hopefully they don't add any university holidays in the near future 4b7aaa70a5284491280b066c5c64ef7a95bff8c7
